# Generated by Django 4.0.4 on 2022-05-21 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OPCenter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadform',
            name='author',
        ),
        migrations.RemoveField(
            model_name='loadform',
            name='title',
        ),
    ]
